version: "3.8"
services:
  app:
    build: .
    container_name: vapor_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: vapor_db
    environment:
      POSTGRES_USER: vapor
      POSTGRES_PASSWORD: vapor
      POSTGRES_DB: vapor
    ports:
      - "5432:5432"
    restart: unless-stopped