version: "3.8"
services:
  app:
    image: picolor-backend-swift
    build: .
    container_name: vapor_app
    ports:
      - "8080:8080"
    env_file:
      - .env
    # volumes:
    #   - .:/app
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080"]
